name: build/test
on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17.6
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.6
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies & install
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go install -v .
        curl -fsSLO https://github.com/open-policy-agent/conftest/releases/download/v0.30.0/conftest_0.30.0_Linux_x86_64.tar.gz
        tar -C /usr/local/bin -xzvf conftest_0.30.0_Linux_x86_64.tar.gz
        wget -q https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
        tar xf kubeval-linux-amd64.tar.gz
        sudo cp kubeval /usr/local/bin
    - name: Setup kind
      uses: engineerd/setup-kind@v0.5.0
    - name: Run Kubernetes tests
      run: |
        kubectl cluster-info
        export PATH="$(go env GOPATH)/bin:$PATH"
        tests/k8s.sh
